# Domotique Stack
# Services: Home Assistant, Zigbee2MQTT, Mosquitto MQTT, Home Assistant Proxy

services:
  # Mosquitto MQTT Broker
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - mosquitto_config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    networks:
      - homeassistant_net
    environment:
      - TZ=${TZ}

  # Zigbee2MQTT
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    restart: unless-stopped
    volumes:
      - zigbee2mqtt_config:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8123
    environment:
      - TZ=${TZ}
    devices:
      - ${ZIGBEE_DONGLE_PATH}:/dev/ttyUSB0
    networks:
      - homeassistant_net
    depends_on:
      - mosquitto

  # Home Assistant
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    network_mode: host
    volumes:
      - homeassistant_config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    environment:
      - TZ=${TZ}
    devices:
      - ${ZIGBEE_DONGLE_PATH}:/dev/ttyUSB0
    labels:
      - "traefik.enable=false"
    depends_on:
      - mosquitto
      - zigbee2mqtt

  # Proxy pour Home Assistant (permet l'accès via Traefik)
  homeassistant-proxy:
    image: nginx:alpine
    container_name: homeassistant-proxy
    restart: unless-stopped
    volumes:
      - ./configs/nginx-ha.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant.rule=Host(`home.${DOMAIN_BASE}`)"
      - "traefik.http.routers.homeassistant.entrypoints=websecure"
      - "traefik.http.routers.homeassistant.tls=true"
      - "traefik.http.routers.homeassistant.tls.certresolver=letsEncrypt"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_net"
    depends_on:
      - homeassistant

networks:
  traefik_net:
    name: traefik_net
    external: true
  homeassistant_net:
    name: homeassistant_net

volumes:
  homeassistant_config:
  zigbee2mqtt_config:
  mosquitto_config:
  mosquitto_data:
  mosquitto_log:
