# Media Stack
# Services: Plex (media server), Overseerr (media requests)

services:
  # Plex - Media Server
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    networks:
      - traefik_net
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
      - TZ=${TZ}
    volumes:
      - plex_config:/config
      - "${MEDIA_PATH}:/media"
      - /dev/shm:/dev/shm
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`plex.${DOMAIN_BASE}`)"
      - "traefik.http.routers.plex.entrypoints=websecure"
      - "traefik.http.routers.plex.tls=true"
      - "traefik.http.routers.plex.tls.certresolver=letsEncrypt"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"

  # Overseerr - Demandes de médias
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - LOG_LEVEL=info
      - TZ=${TZ}
    volumes:
      - overseerr_config:/config
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr.rule=Host(`overseerr.${DOMAIN_BASE}`)"
      - "traefik.http.routers.overseerr.entrypoints=websecure"
      - "traefik.http.routers.overseerr.tls=true"
      - "traefik.http.routers.overseerr.tls.certresolver=letsEncrypt"
      - "traefik.http.services.overseerr.loadbalancer.server.port=5055"
      - "traefik.docker.network=traefik_net"
    depends_on:
      - plex

networks:
  traefik_net:
    name: traefik_net
    external: true

volumes:
  plex_config:
  overseerr_config:
