# RSS Stack
# Services: RSSHub (RSS generator), FreshRSS (RSS reader)

services:
  # RSSHub - RSS Generator
  rsshub:
    container_name: rsshub
    image: diygod/rsshub
    restart: unless-stopped
    networks:
      - traefik_net
    environment:
      - NODE_ENV=production
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rsshub.rule=Host(`rsshub.${DOMAIN_BASE}`)"
      - "traefik.http.routers.rsshub.entrypoints=websecure"
      - "traefik.http.routers.rsshub.tls=true"
      - "traefik.http.routers.rsshub.tls.certresolver=letsEncrypt"
      - "traefik.http.services.rsshub.loadbalancer.server.port=1200"

  # FreshRSS - RSS Reader
  freshrss:
    container_name: freshrss
    image: freshrss/freshrss
    restart: unless-stopped
    networks:
      - traefik_net
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - environment=development
    volumes:
      - freshrss_data:/var/www/FreshRSS/data
      - freshrss_extensions:/var/www/FreshRSS/extensions
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.freshrss.rule=Host(`rss.${DOMAIN_BASE}`)"
      - "traefik.http.routers.freshrss.entrypoints=websecure"
      - "traefik.http.routers.freshrss.tls.certresolver=letsEncrypt"
      - "traefik.http.services.freshrss.loadbalancer.server.port=80"
    depends_on:
      - rsshub

networks:
  traefik_net:
    name: traefik_net
    external: true

volumes:
  freshrss_data:
  freshrss_extensions:
