# Storage Stack
# Services: Samba (file sharing)

services:
  # Samba - Partage de fichiers
  samba:
    image: dperson/samba
    container_name: samba
    ports:
      - "139:139/tcp"
      - "445:445/tcp"
    volumes:
      - samba_config:/etc/samba
      - samba_logs:/var/log/samba
      - "${HDD_PATH}:/mount"
      - "./init.sh:/init.sh" # Monte le script d'initialisation
    environment:
      - USERID=1000
      - GROUPID=1001
      - TZ=${TZ}
    command: ["/bin/sh", "-c", "/init.sh && /usr/sbin/smbd -F"]
    restart: unless-stopped

volumes:
  samba_config:
  samba_logs:
